import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, Phone, ShieldCheck, Stethoscope, UserRound, X } from "lucide-react";
import { login, register, requestPasswordOtp, resetPassword, verifyPasswordOtp } from "../../api";
import "./AuthGate.css";

const benefits = ["Private, encrypted care access", "Certified doctors and local partners", "One calm place for every care moment"];
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const phonePattern = /^(?:\+91[\s-]?|0)?[6-9]\d{9}$/;

function AuthGate({ isOpen = false, initialMode = "login", onClose, onAuthSuccess }) {
  const [mode, setMode] = useState(initialMode);
  const [formData, setFormData] = useState({ fullName: "", identifier: "", password: "", confirmPassword: "", email: "", phone: "", role: "PATIENT", otp: "", channel: "email", resetToken: "" });
  const [errors, setErrors] = useState({});
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  useEffect(() => { setMode(initialMode); setErrors({}); setMessage(""); setShowPassword(false); }, [initialMode, isOpen]);
  const handleChange = (event) => { const { name, value } = event.target; setFormData((current) => ({ ...current, [name]: value })); setErrors((current) => ({ ...current, [name]: "", form: "" })); };
  const switchMode = (nextMode) => { setMode(nextMode); setErrors({}); setMessage(""); };
const validateRegistration = () => { const next = {}; if (!formData.fullName.trim()) next.fullName = "Enter your full name."; if (formData.password.length < 8) next.password = "Use at least 8 characters."; if (!emailPattern.test(formData.email.trim())) next.email = "Enter a valid email address."; if (!phonePattern.test(formData.phone.replace(/[\s-]/g, ""))) next.phone = "Enter a valid Indian mobile number."; if (formData.password !== formData.confirmPassword) next.confirmPassword = "Passwords do not match."; return next; };
  const validateLogin = () => { const next = {}; if (!formData.identifier.trim()) next.identifier = "Enter your email address or mobile number."; if (!formData.password) next.password = "Enter your password."; return next; };

  const handleSubmit = async (event) => {
    event.preventDefault(); setErrors({}); setMessage(""); const validationErrors = mode === "register" ? validateRegistration() : validateLogin(); if (Object.keys(validationErrors).length) { setErrors(validationErrors); return; } setLoading(true);
    try { const auth = mode === "login" ? await login(formData.identifier.trim(), formData.password) : await register(formData.fullName.trim(), formData.password, formData.role, formData.email.trim(), formData.phone.trim()); onAuthSuccess?.(auth); onClose?.(); }
    catch (requestError) { setErrors({ form: requestError.message || "Unable to connect to the healthcare API." }); } finally { setLoading(false); }
  };

  const requestOtp = async (event) => {
    event.preventDefault(); setErrors({}); setMessage(""); if (!formData.identifier.trim()) { setErrors({ identifier: "Enter your username or email." }); return; } setLoading(true);
    try { const result = await requestPasswordOtp(formData.identifier.trim(), formData.channel); const developmentHint = result.developmentOtp ? ` Development OTP: ${result.developmentOtp}` : ""; setMessage(`A one-time code was sent via ${result.channel} to ${result.destination}. It expires in 10 minutes.${developmentHint}`); setMode("verify-otp"); }
    catch (requestError) { setErrors({ form: requestError.message || "We could not send an OTP for that account." }); } finally { setLoading(false); }
  };

  const verifyOtp = async (event) => {
    event.preventDefault(); setErrors({}); setMessage(""); if (!/^\d{6}$/.test(formData.otp.trim())) { setErrors({ otp: "Enter the six-digit OTP." }); return; } setLoading(true);
    try { const resetToken = await verifyPasswordOtp(formData.identifier.trim(), formData.otp.trim()); setFormData((current) => ({ ...current, resetToken })); setMessage("OTP verified. Choose a new password."); setMode("reset"); }
    catch (requestError) { setErrors({ form: requestError.message || "That OTP is invalid or expired." }); } finally { setLoading(false); }
  };

  const handleResetPassword = async (event) => {
    event.preventDefault(); const next = {}; if (formData.password.length < 8) next.password = "Use at least 8 characters."; if (formData.password !== formData.confirmPassword) next.confirmPassword = "Passwords do not match."; if (Object.keys(next).length) { setErrors(next); return; } setLoading(true); setErrors({});
    try { await resetPassword(formData.resetToken, formData.password); setMessage("Your password has been reset. You can now sign in."); setMode("login"); setFormData((current) => ({ ...current, password: "", confirmPassword: "", otp: "" })); }
    catch (requestError) { setErrors({ form: requestError.message || "We could not reset your password." }); } finally { setLoading(false); }
  };

  if (!isOpen) return null;
  const recoveryMode = ["forgot", "verify-otp", "reset"].includes(mode);
  const title = mode === "login" ? "Sign in to your care space" : mode === "register" ? "Create your care account" : mode === "forgot" ? "Recover your care account" : mode === "verify-otp" ? "Verify your one-time code" : "Choose a new password";
  const subtitle = mode === "login" ? "Pick up where your healthcare journey left off." : mode === "register" ? "A few details, then a clearer next step for your health." : mode === "forgot" ? "Choose email or SMS and we will send a secure OTP." : mode === "verify-otp" ? "Enter the six-digit code sent to your registered contact." : "Your password can now be updated securely.";

  return <div className="auth-gate-shell" onClick={onClose} role="presentation"><div className="auth-gate-card" onClick={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="auth-title"><button className="auth-close" type="button" onClick={onClose} aria-label="Close authentication dialog"><X size={19} /></button><aside className="auth-side-panel"><div className="auth-side-brand"><span className="auth-logo"><Stethoscope size={21} /></span><span>healthcare<span>-telemedicine</span></span></div><div className="auth-side-copy"><p className="auth-kicker">Your care, connected</p><h2>Feel supported<br /><em>at every step.</em></h2><p>Secure access to doctors, medicines, reminders, and the people helping you live well.</p></div><div className="auth-benefits">{benefits.map((benefit) => <span key={benefit}><CheckCircle2 size={15} /> {benefit}</span>)}</div></aside><section className="auth-form-panel"><div className="auth-mobile-brand"><span className="auth-logo"><Stethoscope size={19} /></span><strong>healthcare<span>-telemedicine</span></strong></div><div className="auth-form-header"><p className="auth-kicker">{recoveryMode ? "Account recovery" : mode === "login" ? "Welcome back" : "Start your care journey"}</p><h1 id="auth-title">{title}</h1><p>{subtitle}</p></div>{!recoveryMode ? <div className="auth-toggle" role="tablist" aria-label="Authentication mode"><button type="button" role="tab" aria-selected={mode === "login"} className={mode === "login" ? "active" : ""} onClick={() => switchMode("login")}>Sign in</button><button type="button" role="tab" aria-selected={mode === "register"} className={mode === "register" ? "active" : ""} onClick={() => switchMode("register")}>Create account</button></div> : null}

{mode === "forgot" ? <form className="auth-form" onSubmit={requestOtp}><Field name="identifier" label="Email or mobile number" icon={<Mail size={15} />} value={formData.identifier} onChange={handleChange} error={errors.identifier} placeholder="you@example.com or +91 98765 43210" /><label><span><ShieldCheck size={15} /> Send code by</span><select name="channel" value={formData.channel} onChange={handleChange}><option value="email">Email</option><option value="sms">SMS</option></select></label><button type="submit" className="auth-submit" disabled={loading}>{loading ? "Sending code…" : "Send one-time code"}<ArrowRight size={17} /></button></form> : null}
{mode === "verify-otp" ? <form className="auth-form" onSubmit={verifyOtp}><Field name="otp" label="Six-digit OTP" icon={<ShieldCheck size={15} />} value={formData.otp} onChange={handleChange} error={errors.otp} placeholder="123456" inputMode="numeric" maxLength="6" /><button type="submit" className="auth-submit" disabled={loading}>{loading ? "Verifying…" : "Verify OTP"}<ArrowRight size={17} /></button><button type="button" className="auth-forgot" onClick={() => switchMode("forgot")}>Try another delivery method</button></form> : null}
{mode === "reset" ? <form className="auth-form" onSubmit={handleResetPassword}><PasswordField name="password" value={formData.password} onChange={handleChange} showPassword={showPassword} setShowPassword={setShowPassword} label="New password" error={errors.password} /><PasswordField name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} showPassword={showPassword} setShowPassword={setShowPassword} label="Confirm new password" error={errors.confirmPassword} /><button type="submit" className="auth-submit" disabled={loading}>{loading ? "Updating…" : "Reset password"}<ArrowRight size={17} /></button></form> : null}
{!recoveryMode ? <form className="auth-form" onSubmit={handleSubmit}>{mode === "login" ? <Field name="identifier" label="Email or mobile number" icon={<UserRound size={15} />} value={formData.identifier} onChange={handleChange} error={errors.identifier} placeholder="you@example.com or +91 98765 43210" type="text" /> : <Field name="fullName" label="User Full Name" icon={<UserRound size={15} />} value={formData.fullName} onChange={handleChange} error={errors.fullName} placeholder="Enter your full name" />}<PasswordField name="password" value={formData.password} onChange={handleChange} showPassword={showPassword} setShowPassword={setShowPassword} label="Password" error={errors.password} />{mode === "register" ? <><Field name="email" label="Email address" icon={<Mail size={15} />} value={formData.email} onChange={handleChange} error={errors.email} placeholder="you@example.com" type="email" /><Field name="phone" label="Mobile Number" icon={<Phone size={15} />} value={formData.phone} onChange={handleChange} error={errors.phone} placeholder="+91 98765 43210" type="tel" /><PasswordField name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} showPassword={showPassword} setShowPassword={setShowPassword} label="Confirm password" error={errors.confirmPassword} /><label><span><Stethoscope size={15} /> I am joining as</span><select name="role" value={formData.role} onChange={handleChange}><option value="PATIENT">Patient</option><option value="DOCTOR">Doctor</option></select></label></> : <div className="auth-helper"><ShieldCheck size={14} /> Your session is protected by secure token access.</div>}<button type="submit" className="auth-submit" disabled={loading}>{loading ? "Connecting…" : mode === "login" ? "Enter my care space" : "Create my account"}<ArrowRight size={17} /></button></form> : null}
{errors.form ? <p className="auth-error" role="alert">{errors.form}</p> : null}{message ? <p className="auth-success" role="status">{message}</p> : null}{mode === "login" ? <button className="auth-forgot" type="button" onClick={() => switchMode("forgot")}>Forgot your password?</button> : null}<p className="auth-switch-copy">{recoveryMode ? <button type="button" onClick={() => switchMode("login")}><ArrowLeft size={13} /> Back to sign in</button> : <>{mode === "login" ? "New to healthcare-telemedicine?" : "Already have an account?"} <button type="button" onClick={() => switchMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "Create one" : "Sign in"}</button></>}</p></section></div></div>;
}

function Field({ name, label, icon, value, onChange, error, placeholder, type = "text", inputMode, maxLength }) { return <label><span>{icon} {label}</span><input name={name} type={type} value={value} onChange={onChange} placeholder={placeholder} inputMode={inputMode} maxLength={maxLength} required aria-invalid={Boolean(error)} />{error ? <small className="field-error">{error}</small> : null}</label>; }
function PasswordField({ name, value, onChange, showPassword, setShowPassword, label, error }) { return <label><span><LockKeyhole size={15} /> {label}</span><div className="password-field"><input name={name} type={showPassword ? "text" : "password"} value={value} onChange={onChange} autoComplete="new-password" placeholder="At least 8 characters" required aria-invalid={Boolean(error)} /><button type="button" onClick={() => setShowPassword((current) => !current)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>{error ? <small className="field-error">{error}</small> : null}</label>; }
export default AuthGate;
